import type { Prompt, PromptCategory, Difficulty } from '@/types'

type PromptSeed = Omit<Prompt, 'id' | 'created_at' | 'active'>

export const PROMPT_SEEDS: PromptSeed[] = [
  // ── SOCIETY ─────────────────────────────────────────────────────────────
  {
    topic: 'Urban Beekeeping',
    category: 'society',
    difficulty: 1,
    stance_type: 'argue',
    prompt_text: 'Should cities actively support urban beekeeping?',
    context_bullets: [
      'Keeping bee colonies in rooftops and community gardens',
      'May improve pollination in parks and urban green spaces',
      'Used in education and community projects',
      'Some ecologists worry about competition with native bee species',
    ],
    retry_angle: 'Explain urban beekeeping to a 12-year-old and why it might be a good or bad idea.',
    tags: ['ecology', 'cities', 'policy'],
  },
  {
    topic: 'Four-Day Work Week',
    category: 'society',
    difficulty: 1,
    stance_type: 'argue',
    prompt_text: 'Is a four-day work week genuinely better for society, or just better for knowledge workers?',
    context_bullets: [
      'Several countries have run four-day week pilots',
      'Productivity often stays flat or improves in trials',
      'Works poorly for shift-based and service industries',
      'Raises questions about who benefits most',
    ],
    retry_angle: 'Imagine you are a nurse or a warehouse worker. Make the case for or against a four-day week from that perspective.',
    tags: ['work', 'economics', 'wellbeing'],
  },
  {
    topic: 'Phone-Free Schools',
    category: 'society',
    difficulty: 1,
    stance_type: 'argue',
    prompt_text: 'Should smartphones be banned during school hours?',
    context_bullets: [
      'France and several US states have introduced bans',
      'Studies link phone use to reduced attention and sleep',
      'Counterarguments around digital literacy and access to information',
      'Enforcement is difficult',
    ],
    retry_angle: 'Make the case for the side you disagree with.',
    tags: ['education', 'technology', 'youth'],
  },
  {
    topic: 'Loneliness as a Public Health Crisis',
    category: 'society',
    difficulty: 2,
    stance_type: 'explain',
    prompt_text: 'Why might governments treat loneliness as a public health issue rather than a private matter?',
    context_bullets: [
      'UK appointed a Minister for Loneliness in 2018',
      'Research links chronic loneliness to heart disease and early death',
      'Social fragmentation has increased in many Western countries',
      'Digital connection does not always substitute for physical presence',
    ],
    retry_angle: 'What would a sceptic say — and how would you respond to them?',
    tags: ['health', 'society', 'government'],
  },
  {
    topic: 'Car-Free City Centres',
    category: 'society',
    difficulty: 1,
    stance_type: 'argue',
    prompt_text: 'What are the strongest arguments for and against removing cars from city centres?',
    context_bullets: [
      'Oslo, Amsterdam and other cities have reduced car access significantly',
      'Linked to improved air quality, pedestrian safety, and local retail',
      'Critics argue it disadvantages elderly and disabled people',
      'May push congestion to surrounding roads',
    ],
    retry_angle: 'You are a shopkeeper on the high street. What is your view?',
    tags: ['transport', 'cities', 'environment'],
  },
  {
    topic: 'Universal Basic Income',
    category: 'society',
    difficulty: 2,
    stance_type: 'argue',
    prompt_text: 'Would a universal basic income solve more problems than it creates?',
    context_bullets: [
      'Finland and Kenya have run UBI pilots with mixed results',
      'Removes means-testing complexity from welfare systems',
      'Raises questions about inflation and work incentives',
      'Funding mechanisms remain deeply contested',
    ],
    retry_angle: 'Explain the concept to someone who has never heard of UBI.',
    tags: ['economics', 'welfare', 'policy'],
  },

  // ── SCIENCE ──────────────────────────────────────────────────────────────
  {
    topic: 'Geoengineering',
    category: 'science',
    difficulty: 3,
    stance_type: 'argue',
    prompt_text: 'Should humanity attempt to deliberately modify the global climate to counteract warming?',
    context_bullets: [
      'Solar radiation management proposals include stratospheric aerosol injection',
      'Could rapidly reduce surface temperatures if deployed',
      'Unilateral deployment could affect rainfall patterns globally',
      'Critics call it a dangerous moral hazard that reduces urgency to cut emissions',
    ],
    retry_angle: 'Explain the core tension in one sentence, then expand on whichever side you find harder to argue.',
    tags: ['climate', 'science', 'ethics', 'policy'],
  },
  {
    topic: 'Lab-Grown Meat',
    category: 'science',
    difficulty: 1,
    stance_type: 'argue',
    prompt_text: 'Should lab-grown meat replace conventional animal farming?',
    context_bullets: [
      'Cultured meat is produced from animal cells without slaughter',
      'Could significantly reduce land use and greenhouse gas emissions',
      'Cost and scale-up remain challenges',
      'Consumer acceptance and regulatory approval vary by country',
    ],
    retry_angle: 'What arguments would a livestock farmer make, and which ones are the strongest?',
    tags: ['food', 'environment', 'technology'],
  },
  {
    topic: 'CRISPR Gene Editing in Humans',
    category: 'science',
    difficulty: 3,
    stance_type: 'argue',
    prompt_text: 'Where should society draw the line on human genetic editing?',
    context_bullets: [
      'CRISPR enables targeted DNA edits with increasing precision',
      'Somatic editing (in adults) is broadly accepted for disease treatment',
      'Germline editing (inheritable changes) remains highly controversial',
      'The 2018 He Jiankui case sparked global scientific condemnation',
    ],
    retry_angle: 'Describe one use case you think should be allowed and one that should not.',
    tags: ['biotech', 'ethics', 'medicine'],
  },
  {
    topic: 'Dark Matter',
    category: 'science',
    difficulty: 3,
    stance_type: 'explain',
    prompt_text: 'How would you explain the concept of dark matter and why scientists believe it exists?',
    context_bullets: [
      'Roughly 27% of the universe is estimated to be dark matter',
      'It does not emit, absorb or reflect light — detected only through gravity',
      'Galaxy rotation curves cannot be explained without additional mass',
      'Its exact nature remains unknown — no direct detection yet',
    ],
    retry_angle: 'Explain it using only an analogy. No technical terms.',
    tags: ['physics', 'cosmology', 'explanation'],
  },
  {
    topic: 'Antibiotic Resistance',
    category: 'science',
    difficulty: 2,
    stance_type: 'explain',
    prompt_text: 'Why is antibiotic resistance considered one of the greatest threats to global health?',
    context_bullets: [
      'Overuse in medicine and livestock accelerates resistance',
      'WHO estimates 700,000 deaths per year currently attributable to resistant infections',
      'The pipeline of new antibiotics has nearly stalled',
      'Drug companies have little financial incentive to develop new ones',
    ],
    retry_angle: 'What should one individual do differently? And does it matter?',
    tags: ['health', 'medicine', 'global'],
  },
  {
    topic: 'Deep Sea Mining',
    category: 'science',
    difficulty: 2,
    stance_type: 'argue',
    prompt_text: 'Should we mine the deep ocean floor for critical minerals needed for clean energy?',
    context_bullets: [
      'Polymetallic nodules on the seabed contain cobalt, nickel and manganese',
      'These are needed for EV batteries and renewable energy technology',
      'Deep sea ecosystems are poorly understood and potentially irreplaceable',
      'International waters governance remains contested',
    ],
    retry_angle: 'Someone says we should protect the deep sea at all costs. What do you say to them?',
    tags: ['environment', 'energy', 'ocean'],
  },

  // ── BUSINESS ─────────────────────────────────────────────────────────────
  {
    topic: 'Founder Mode',
    category: 'business',
    difficulty: 1,
    stance_type: 'argue',
    prompt_text: 'Should startup founders stay deeply operational as companies scale, or hand off to professional managers?',
    context_bullets: [
      'Paul Graham coined "founder mode" as a counter to conventional management advice',
      'Examples like Jobs and Musk operated with deep product involvement at scale',
      'Delegation failure is a real risk — some founders become bottlenecks',
      'Context-dependent: B2B SaaS versus consumer tech may require different models',
    ],
    retry_angle: 'Give a concrete example — real or imagined — of a founder who got this wrong in each direction.',
    tags: ['startups', 'management', 'leadership'],
  },
  {
    topic: 'Purpose-Driven Corporations',
    category: 'business',
    difficulty: 2,
    stance_type: 'argue',
    prompt_text: 'Can a large public company genuinely prioritise social purpose alongside shareholder returns?',
    context_bullets: [
      'The Business Roundtable 2019 statement moved away from shareholder primacy',
      'Patagonia transferred ownership to an environmental trust in 2022',
      'Critics argue purpose-washing is widespread and incentives remain financial',
      'ESG investment has grown significantly but measurement remains inconsistent',
    ],
    retry_angle: 'Name one company you think is genuinely trying, and one you think is not. Explain both.',
    tags: ['business', 'ethics', 'ESG'],
  },
  {
    topic: 'Subscription Fatigue',
    category: 'business',
    difficulty: 1,
    stance_type: 'explain',
    prompt_text: 'Has the subscription economy reached a breaking point, and what happens next?',
    context_bullets: [
      'Average US consumer now pays for more than five subscription services',
      'Churn rates have increased for streaming and SaaS platforms',
      'Bundling strategies are re-emerging as a response',
      'Consumers increasingly resist recurring costs for single-use value',
    ],
    retry_angle: 'What business models do you think will replace pure subscriptions?',
    tags: ['business', 'consumer', 'technology'],
  },
  {
    topic: 'Vertical Integration',
    category: 'business',
    difficulty: 2,
    stance_type: 'explain',
    prompt_text: 'When does it make strategic sense for a company to vertically integrate?',
    context_bullets: [
      'Vertical integration means owning parts of your supply chain',
      'Apple makes its own chips; Amazon runs its own logistics',
      'Increases control and margins but raises capital requirements',
      'Can reduce flexibility and create internal misalignment',
    ],
    retry_angle: 'Give a case where vertical integration clearly backfired.',
    tags: ['strategy', 'operations', 'business'],
  },

  // ── ETHICS ───────────────────────────────────────────────────────────────
  {
    topic: 'Trolley Problem Variants',
    category: 'ethics',
    difficulty: 2,
    stance_type: 'argue',
    prompt_text: 'Is there a meaningful moral difference between actively causing harm and allowing harm to happen?',
    context_bullets: [
      'The trolley problem frames this as pulling a lever versus doing nothing',
      'Consequentialists focus on outcomes; deontologists focus on actions',
      'Medical ethics applies this constantly: withdrawal of treatment versus euthanasia',
      'Most people intuitively feel there is a difference even when outcomes are identical',
    ],
    retry_angle: 'Describe a real-world scenario where this distinction is legally or morally significant.',
    tags: ['ethics', 'philosophy', 'law'],
  },
  {
    topic: 'Obligatory Altruism',
    category: 'ethics',
    difficulty: 3,
    stance_type: 'argue',
    prompt_text: 'Do affluent people have a moral obligation to give significantly to global poverty relief?',
    context_bullets: [
      'Peter Singer\'s "drowning child" argument extends across distance',
      'Effective altruism calculates marginal utility of donations across causes',
      'Critics argue it demands too much and ignores local obligations',
      'The question of how much is "enough" has no clean answer',
    ],
    retry_angle: 'What objection to Singer\'s argument do you find most persuasive, and why?',
    tags: ['ethics', 'philosophy', 'poverty', 'giving'],
  },
  {
    topic: 'AI Moral Status',
    category: 'ethics',
    difficulty: 3,
    stance_type: 'argue',
    prompt_text: 'Could an AI system ever deserve moral consideration — and if so, what would that require?',
    context_bullets: [
      'Moral status usually requires sentience: the ability to suffer or experience',
      'Large language models exhibit no confirmed internal experience',
      'The hard problem of consciousness means we cannot verify subjective states from behaviour',
      'Some philosophers argue functional analogues to emotion may be sufficient',
    ],
    retry_angle: 'Argue the position you find least plausible.',
    tags: ['AI', 'ethics', 'philosophy', 'consciousness'],
  },
  {
    topic: 'Privacy vs Safety',
    category: 'ethics',
    difficulty: 2,
    stance_type: 'argue',
    prompt_text: 'When, if ever, is it justified for governments to surveil citizens without consent?',
    context_bullets: [
      'Mass surveillance programmes were revealed by Snowden in 2013',
      'Proponents argue it prevents terrorism and serious crime',
      'Critics argue it chills free speech and is disproportionate',
      'Effectiveness evidence is contested',
    ],
    retry_angle: 'Draw a specific line: surveillance of what type, with what oversight, is acceptable?',
    tags: ['privacy', 'law', 'technology', 'government'],
  },

  // ── TECHNOLOGY ───────────────────────────────────────────────────────────
  {
    topic: 'Open Source AI Models',
    category: 'technology',
    difficulty: 2,
    stance_type: 'argue',
    prompt_text: 'Should powerful AI models be open-sourced, or does that pose unacceptable risks?',
    context_bullets: [
      'Meta\'s Llama models are open weights; OpenAI and Anthropic keep weights closed',
      'Open models allow safety research, localisation, and independent study',
      'They also allow fine-tuning for harmful uses without guardrails',
      'The dual-use tension mirrors debates about open-source security tools',
    ],
    retry_angle: 'What conditions, if any, would make you comfortable with fully open powerful models?',
    tags: ['AI', 'safety', 'technology', 'policy'],
  },
  {
    topic: 'Attention Economy',
    category: 'technology',
    difficulty: 2,
    stance_type: 'argue',
    prompt_text: 'Are social media platforms structurally incapable of acting in users\' genuine interests?',
    context_bullets: [
      'Platforms are optimised for engagement, not wellbeing',
      'Internal documents at Meta showed awareness of Instagram\'s effects on teenage girls',
      'Regulatory pressure is increasing in EU and US',
      'Some argue better design choices are possible without destroying business models',
    ],
    retry_angle: 'Design one specific change to a major platform that would improve this.',
    tags: ['technology', 'social media', 'regulation'],
  },
  {
    topic: 'Autonomous Weapons',
    category: 'technology',
    difficulty: 3,
    stance_type: 'argue',
    prompt_text: 'Should lethal autonomous weapons systems be banned under international law?',
    context_bullets: [
      'AWS can select and engage targets without human decision at the moment of kill',
      'Proponents argue they reduce soldier casualties and increase precision',
      'Critics argue accountability, distinction of civilians, and proportionality cannot be preserved',
      'No binding international law currently prohibits them',
    ],
    retry_angle: 'Compare the ethics of autonomous weapons to the ethics of landmines.',
    tags: ['AI', 'warfare', 'law', 'ethics'],
  },
  {
    topic: 'Crypto Utility',
    category: 'technology',
    difficulty: 2,
    stance_type: 'argue',
    prompt_text: 'Beyond speculation, what is the strongest legitimate use case for cryptocurrency today?',
    context_bullets: [
      'Bitcoin was designed as a censorship-resistant peer-to-peer payment system',
      'Stablecoins are used for remittances in countries with weak banking infrastructure',
      'DeFi promises open financial infrastructure but has seen significant fraud',
      'Most trading volume is speculative rather than utility-driven',
    ],
    retry_angle: 'Assume cryptocurrency as a technology is here to stay. Where should regulation focus?',
    tags: ['crypto', 'finance', 'technology'],
  },
  {
    topic: 'Remote Work Long-Term',
    category: 'technology',
    difficulty: 1,
    stance_type: 'argue',
    prompt_text: 'Have the long-term costs of remote work outweighed the benefits?',
    context_bullets: [
      'Remote work reduced commuting and expanded talent pools geographically',
      'Studies show mixed results on productivity across job types',
      'Collaboration, mentorship and culture formation appear harder remotely',
      'Many companies have reversed remote-first policies in 2023-24',
    ],
    retry_angle: 'Who benefits most and who loses most from remote work? Is that the right lens?',
    tags: ['work', 'technology', 'management'],
  },

  // ── CULTURE ──────────────────────────────────────────────────────────────
  {
    topic: 'Cultural Appropriation',
    category: 'culture',
    difficulty: 2,
    stance_type: 'argue',
    prompt_text: 'Is there a meaningful distinction between cultural appropriation and cultural exchange?',
    context_bullets: [
      'Critics focus on power imbalances and commercial exploitation',
      'Defenders argue all culture is historically mixed and exchange enriches everyone',
      'Context matters: wearing a Halloween costume vs. high fashion borrowing from indigenous art',
      'Hard to police without essentialising cultures as static and bounded',
    ],
    retry_angle: 'Give one example of clearly acceptable exchange and one of clearly problematic appropriation.',
    tags: ['culture', 'ethics', 'identity'],
  },
  {
    topic: 'Streaming and the Music Industry',
    category: 'culture',
    difficulty: 1,
    stance_type: 'argue',
    prompt_text: 'Has streaming been good or bad for musicians?',
    context_bullets: [
      'Spotify pays roughly $0.003-0.005 per stream',
      'Streaming massively increased music consumption and discovery',
      'Revenue concentration among top 1% of artists has increased',
      'Touring has become more important to revenue for working musicians',
    ],
    retry_angle: 'Design a better streaming royalty model.',
    tags: ['music', 'business', 'culture'],
  },
  {
    topic: 'Nostalgia Economy',
    category: 'culture',
    difficulty: 2,
    stance_type: 'explain',
    prompt_text: 'Why does so much modern entertainment recycle IP and nostalgia rather than create new things?',
    context_bullets: [
      'Disney, Warner Bros and others have relied heavily on sequels and reboots',
      'Risk aversion at studios increases as production costs rise',
      'Pre-existing IP has built-in audiences in fragmented attention markets',
      'Critics argue it crowds out original voices and stagnates culture',
    ],
    retry_angle: 'Name one recent creative work that broke the pattern. What made it possible?',
    tags: ['entertainment', 'culture', 'business'],
  },

  // ── HISTORY ──────────────────────────────────────────────────────────────
  {
    topic: 'Reparations for Historical Injustices',
    category: 'history',
    difficulty: 3,
    stance_type: 'argue',
    prompt_text: 'Can reparations for historical injustices like slavery ever be practically or morally meaningful?',
    context_bullets: [
      'Several US cities and states are studying reparations frameworks',
      'Germany has paid reparations to Holocaust survivors',
      'Questions of who pays, who receives, and over what time horizon are contested',
      'Some argue structural reform is more meaningful than direct payments',
    ],
    retry_angle: 'Separate the moral question from the practical one. Which is easier to answer?',
    tags: ['history', 'ethics', 'race', 'policy'],
  },
  {
    topic: 'Lessons from the Roman Empire',
    category: 'history',
    difficulty: 2,
    stance_type: 'explain',
    prompt_text: 'What is the most relevant lesson that modern democracies should take from the fall of Rome?',
    context_bullets: [
      'Rome transitioned from republic to empire under internal political pressures',
      'Overextension, economic strain, and institutional decay all played roles',
      'The fall was gradual, contested, and is still debated by historians',
      'Various modern parallels have been drawn, though often contested',
    ],
    retry_angle: 'Which analogy do you find most clearly overstated?',
    tags: ['history', 'politics', 'institutions'],
  },
  {
    topic: 'Cold War Space Race',
    category: 'history',
    difficulty: 1,
    stance_type: 'explain',
    prompt_text: 'Was the Cold War space race ultimately good for humanity?',
    context_bullets: [
      'Led to Apollo programme, satellite communications, and GPS',
      'Driven primarily by military competition, not scientific idealism',
      'Resources spent might have addressed more immediate human problems',
      'Created scientific and engineering infrastructure that persists today',
    ],
    retry_angle: 'What would we have lost if neither side had competed?',
    tags: ['history', 'science', 'geopolitics'],
  },

  // ── ABSURD BUT ANSWERABLE ─────────────────────────────────────────────────
  {
    topic: 'Optimism as Strategy',
    category: 'absurd',
    difficulty: 2,
    stance_type: 'argue',
    prompt_text: 'Is optimism a rational strategy or a cognitive bias we should overcome?',
    context_bullets: [
      'The optimism bias is well-documented: people overestimate positive outcomes',
      'Research links optimism to better health, resilience, and negotiation outcomes',
      'Unrealistic optimism causes poor planning and risk management',
      'Defensive pessimism is a legitimate alternative strategy for some people',
    ],
    retry_angle: 'When does optimism become delusional? Give a specific threshold.',
    tags: ['psychology', 'decision-making', 'strategy'],
  },
  {
    topic: 'Boredom',
    category: 'absurd',
    difficulty: 2,
    stance_type: 'argue',
    prompt_text: 'Is boredom underrated — and should we protect it?',
    context_bullets: [
      'Research links unstructured boredom to creativity and problem-solving',
      'Smartphones have nearly eliminated idle, unstimulated time',
      'Schools and employers often treat boredom as a failure state',
      'Children\'s unsupervised play has declined dramatically since the 1980s',
    ],
    retry_angle: 'Design a policy that would protect or restore boredom in modern life.',
    tags: ['psychology', 'culture', 'technology'],
  },
  {
    topic: 'The Value of Useless Knowledge',
    category: 'absurd',
    difficulty: 2,
    stance_type: 'argue',
    prompt_text: 'Should universities defend education that has no obvious economic utility?',
    context_bullets: [
      'Humanities enrolments are declining across English-speaking countries',
      'Governments increasingly tie funding to graduate employment outcomes',
      'Many foundational discoveries came from "useless" pure research',
      'Some argue liberal arts develops critical thinking that transfers broadly',
    ],
    retry_angle: 'Name a field that seems useless, then make the strongest possible case for it.',
    tags: ['education', 'culture', 'economics'],
  },
  {
    topic: 'Rules vs Intuition',
    category: 'absurd',
    difficulty: 3,
    stance_type: 'argue',
    prompt_text: 'Should you follow a rule you know is wrong in a specific situation?',
    context_bullets: [
      'Rules exist because individual judgement is often biased and self-serving',
      'Exceptions that seem obvious often lead to rule breakdown over time',
      'Emergency ethics literature explores this: when should doctors break confidentiality?',
      'Bureaucratic rule-following has caused documented harms in history',
    ],
    retry_angle: 'Give a situation where breaking the rule was clearly right, and one where it was clearly wrong.',
    tags: ['ethics', 'philosophy', 'decision-making'],
  },
  {
    topic: 'Silence in Conversations',
    category: 'absurd',
    difficulty: 1,
    stance_type: 'explain',
    prompt_text: 'Why are people so uncomfortable with silence in conversation, and should we try to change that?',
    context_bullets: [
      'Research shows people fill silences within 200ms on average',
      'Cultural norms vary significantly — some cultures treat silence as respect',
      'Silence intolerance may be linked to anxiety and self-consciousness',
      'Active listening involves tolerating silence to allow the other person to think',
    ],
    retry_angle: 'Describe a specific type of conversation where silence would be powerful.',
    tags: ['psychology', 'communication', 'culture'],
  },

  // ── INTERVIEW ─────────────────────────────────────────────────────────────
  {
    topic: 'Your Greatest Weakness',
    category: 'interview',
    difficulty: 1,
    stance_type: 'explain',
    prompt_text: 'Tell me about a significant professional weakness and what you have done about it.',
    context_bullets: [
      'Interviewers are testing self-awareness and honesty',
      'They want real weaknesses, not strengths in disguise',
      'Evidence of action taken on the weakness matters',
      'Balance: honest without disqualifying',
    ],
    retry_angle: 'Answer it for a completely different weakness.',
    tags: ['interview', 'self-awareness', 'career'],
  },
  {
    topic: 'Failure and Learning',
    category: 'interview',
    difficulty: 1,
    stance_type: 'explain',
    prompt_text: 'Describe a significant failure and what it taught you.',
    context_bullets: [
      'Be specific about your role in the failure',
      'Focus on what you personally did differently after',
      'Interviewers are testing accountability and growth mindset',
      'Avoid blaming others or minimising your own contribution',
    ],
    retry_angle: 'What is a smaller failure that had a disproportionate impact on how you work?',
    tags: ['interview', 'growth', 'self-awareness'],
  },
  {
    topic: 'Disagree with a Manager',
    category: 'interview',
    difficulty: 2,
    stance_type: 'explain',
    prompt_text: 'Tell me about a time you disagreed with your manager and how you handled it.',
    context_bullets: [
      'Tests assertiveness, diplomatic communication, and professional maturity',
      'Interviewers want to see you can push back constructively',
      'Outcome matters but process matters more',
      'Avoid stories that make you sound difficult or your manager incompetent',
    ],
    retry_angle: 'What did the experience teach you about how to raise disagreement effectively?',
    tags: ['interview', 'leadership', 'communication'],
  },
  {
    topic: 'Why This Company',
    category: 'interview',
    difficulty: 1,
    stance_type: 'explain',
    prompt_text: 'Why do you want to work here specifically, rather than at a competitor?',
    context_bullets: [
      'Tests genuine research and motivation versus generic enthusiasm',
      'Interviewers want specificity: product, culture, mission, or problem',
      'Linking your background to their specific needs is powerful',
      'Flattery without substance scores poorly',
    ],
    retry_angle: 'What would make you turn this offer down?',
    tags: ['interview', 'motivation', 'career'],
  },

  // ── DEBATE ────────────────────────────────────────────────────────────────
  {
    topic: 'Meritocracy',
    category: 'debate',
    difficulty: 3,
    stance_type: 'argue',
    prompt_text: 'Is meritocracy a genuine system of fairness or a way of legitimising existing advantages?',
    context_bullets: [
      'Coined by Michael Young in 1958 as a satirical warning, not an ideal',
      'Research shows family background strongly predicts outcomes even in high-mobility countries',
      'Believers argue it at least moves beyond hereditary privilege',
      'Critics argue it disguises luck and structural advantage as personal virtue',
    ],
    retry_angle: 'What would a truly fair selection system look like, practically?',
    tags: ['society', 'ethics', 'economics', 'debate'],
  },
  {
    topic: 'Immigration and Public Opinion',
    category: 'debate',
    difficulty: 2,
    stance_type: 'argue',
    prompt_text: 'Should immigration policy be based primarily on economic needs or humanitarian obligations?',
    context_bullets: [
      'Economic models show net positive effects of immigration in most OECD countries',
      'Humanitarian frameworks emphasise rights and obligations to asylum seekers',
      'Skilled worker visas prioritise economic utility explicitly',
      'Political backlash has often focused on cultural rather than economic concerns',
    ],
    retry_angle: 'Choose one of these frameworks and identify its most serious blind spot.',
    tags: ['politics', 'society', 'ethics', 'debate'],
  },
  {
    topic: 'Free Speech Limits',
    category: 'debate',
    difficulty: 2,
    stance_type: 'argue',
    prompt_text: 'Where should the line be drawn on what speech is acceptable in a democracy?',
    context_bullets: [
      'First Amendment absolutism contrasts with European hate speech laws',
      'Platforms now make de facto speech policy through moderation decisions',
      'Incitement to violence is almost universally restricted',
      'Disinformation and coordinated inauthentic behaviour raise new challenges',
    ],
    retry_angle: 'Describe one type of speech you find offensive but would defend the right to make.',
    tags: ['politics', 'law', 'ethics', 'debate'],
  },

  // ── PRESSURE SIMULATION (Difficulty 4) ────────────────────────────────────
  {
    topic: 'Nothing',
    category: 'absurd',
    difficulty: 4,
    stance_type: 'explain',
    prompt_text: 'What is the philosophical concept of nothingness, and can it exist?',
    context_bullets: [
      'The vacuum of space still contains quantum fluctuations',
      'Parmenides argued nothing cannot exist because to speak of it gives it being',
      'Buddhist concepts of emptiness differ from Western philosophical nothing',
      'Physics treats the vacuum as a quantum field, not absence',
    ],
    retry_angle: 'Try describing nothingness without using the word "nothing" or "empty".',
    tags: ['philosophy', 'physics', 'absurd'],
  },
  {
    topic: 'The Ship of Theseus',
    category: 'absurd',
    difficulty: 3,
    stance_type: 'argue',
    prompt_text: 'If you replace every part of something, is it still the same thing? Does the answer change for people?',
    context_bullets: [
      'The ship of Theseus paradox asks about identity through change',
      'Human cells are largely replaced over years; neurons persist longer',
      'Legal identity persists despite physical change',
      'The question matters in: transplants, AI continuity, corporate identity, art authentication',
    ],
    retry_angle: 'Apply this to personal identity: are you the same person you were at age 10?',
    tags: ['philosophy', 'identity', 'absurd'],
  },
  {
    topic: 'Being Wrong',
    category: 'absurd',
    difficulty: 4,
    stance_type: 'argue',
    prompt_text: 'Make the best possible argument that it is good to be wrong.',
    context_bullets: [
      'Being wrong provides information that being right does not',
      'Cultures that punish wrongness reduce risk-taking and disclosure',
      'Scientific progress depends on falsifiability: experiments designed to fail',
      'Kathryn Schulz argues being wrong feels exactly like being right until it does not',
    ],
    retry_angle: 'How does this apply to how you personally learn?',
    tags: ['psychology', 'growth', 'absurd'],
  },
  {
    topic: 'Convince Me in 60 Seconds',
    category: 'debate',
    difficulty: 4,
    stance_type: 'argue',
    prompt_text: 'Convince me that something most people consider boring is secretly fascinating.',
    context_bullets: [
      'Choose any topic: tax law, concrete, sand, spreadsheets',
      'Constraint: you cannot use the word "actually"',
      'You have 60 seconds and no preparation',
      'The test is whether you can generate genuine interest, not fake enthusiasm',
    ],
    retry_angle: 'Pick a different "boring" topic and go again.',
    tags: ['communication', 'creativity', 'debate', 'pressure'],
  },
  {
    topic: 'Unknown Unknown',
    category: 'absurd',
    difficulty: 4,
    stance_type: 'explain',
    prompt_text: 'Explain what a "known unknown" is versus an "unknown unknown" — and why the distinction matters.',
    context_bullets: [
      'Coined by Donald Rumsfeld in a 2002 press briefing',
      'Known unknowns: risks you know you cannot predict (weather in a year)',
      'Unknown unknowns: risks you do not know you cannot predict (black swans)',
      'Risk management frameworks handle the first well and the second poorly',
    ],
    retry_angle: 'Give one example of an unknown unknown that became known in the last 20 years.',
    tags: ['philosophy', 'decision-making', 'risk', 'absurd'],
  },

  // ── ADDITIONAL PROMPTS ────────────────────────────────────────────────────
  {
    topic: 'Nuclear Energy Revival',
    category: 'science',
    difficulty: 2,
    stance_type: 'argue',
    prompt_text: 'Should nuclear energy be central to the clean energy transition?',
    context_bullets: [
      'Nuclear produces no direct carbon emissions during operation',
      'Three Mile Island, Chernobyl, and Fukushima shaped public perception strongly',
      'New small modular reactor designs promise cheaper, faster builds',
      'Waste storage remains a politically and technically unsolved problem',
    ],
    retry_angle: 'Steelman the anti-nuclear case using only evidence from after 2010.',
    tags: ['energy', 'environment', 'policy'],
  },
  {
    topic: 'Digital Nomadism',
    category: 'culture',
    difficulty: 1,
    stance_type: 'argue',
    prompt_text: 'Is digital nomadism a lifestyle to emulate or a symptom of social disconnection?',
    context_bullets: [
      'An estimated 35 million people identify as digital nomads globally',
      'Enabled by remote work and low-cost international living arbitrage',
      'Critics argue it hollows out local communities in popular destinations',
      'Proponents argue it expands access to global experience and culture',
    ],
    retry_angle: 'What would you lose that you cannot replace if you lived this way permanently?',
    tags: ['culture', 'work', 'travel', 'society'],
  },
  {
    topic: 'The Expertise Gap',
    category: 'society',
    difficulty: 2,
    stance_type: 'explain',
    prompt_text: 'Why do people increasingly distrust experts, and is that distrust sometimes justified?',
    context_bullets: [
      'Trust in scientific and medical institutions fell sharply in 2020-22',
      'Some expert consensus has historically been wrong (ulcer bacteria, dietary fat)',
      'Social media enables rapid critique and amplification of expert errors',
      'Technocracy risks removing political decisions from democratic accountability',
    ],
    retry_angle: 'When should a non-expert distrust an expert? What would make that reasonable?',
    tags: ['society', 'knowledge', 'democracy'],
  },
  {
    topic: 'Sleep and Productivity',
    category: 'science',
    difficulty: 1,
    stance_type: 'argue',
    prompt_text: 'Has the corporate culture of undervaluing sleep caused measurable harm?',
    context_bullets: [
      'Matthew Walker\'s research argues sleep deprivation impairs cognition severely',
      'Hustle culture explicitly glorified minimal sleep for decades',
      'Some industries (medicine, military) structurally require sleep deprivation',
      'Economic costs of impaired judgment from tiredness are difficult to quantify',
    ],
    retry_angle: 'What would change if companies officially treated sleep as a performance input?',
    tags: ['health', 'work', 'culture'],
  },
  {
    topic: 'Persuasion vs Manipulation',
    category: 'ethics',
    difficulty: 3,
    stance_type: 'argue',
    prompt_text: 'What is the difference between persuasion and manipulation? Is there a clean line?',
    context_bullets: [
      'Both aim to change beliefs or behaviours without force',
      'Classical distinction: persuasion appeals to reason; manipulation bypasses it',
      'Advertising, political campaigns, and therapists all operate in a grey area',
      'Informed consent is one proposed criterion: does the target know what is happening?',
    ],
    retry_angle: 'Is self-persuasion (reframing for motivation) manipulation?',
    tags: ['ethics', 'communication', 'psychology'],
  },
  {
    topic: 'Second Languages',
    category: 'culture',
    difficulty: 1,
    stance_type: 'argue',
    prompt_text: 'Is learning a second language still worth the investment in an age of AI translation?',
    context_bullets: [
      'Real-time AI translation quality has improved dramatically',
      'Research shows bilingualism has cognitive benefits beyond communication',
      'Language shapes how you think, not just what you can say',
      'Professional contexts still value native-level fluency in key languages',
    ],
    retry_angle: 'Which arguments for language learning survive if AI translation becomes perfect?',
    tags: ['language', 'culture', 'technology'],
  },
  {
    topic: 'The Midlife Crisis',
    category: 'culture',
    difficulty: 2,
    stance_type: 'explain',
    prompt_text: 'Is the midlife crisis a real psychological phenomenon or a cultural construct?',
    context_bullets: [
      'Coined by Elliott Jaques in 1965 from clinical psychoanalytic work',
      'Research on U-shaped happiness curves across age has mixed support',
      'The form it takes (sports car, affair) is clearly culturally specific',
      'Some argue it reflects genuine confrontation with mortality and unlived life',
    ],
    retry_angle: 'What would the equivalent experience look like in a culture without individual retirement?',
    tags: ['psychology', 'culture', 'ageing'],
  },
  {
    topic: 'Wilderness',
    category: 'ethics',
    difficulty: 2,
    stance_type: 'argue',
    prompt_text: 'Does wilderness have intrinsic value independent of its usefulness to humans?',
    context_bullets: [
      'Deep ecology argues non-human nature has value regardless of human interests',
      'Environmental law in many countries attributes rights to natural entities',
      'The "services" framework values nature instrumentally: clean water, carbon sequestration',
      'Ecuador and New Zealand have granted legal rights to rivers',
    ],
    retry_angle: 'What would your answer require you to give up?',
    tags: ['environment', 'ethics', 'law', 'philosophy'],
  },
  {
    topic: 'The Death of Serendipity',
    category: 'culture',
    difficulty: 3,
    stance_type: 'argue',
    prompt_text: 'Have algorithmic recommendation systems reduced the role of serendipity in culture?',
    context_bullets: [
      'Streaming platforms optimise for continued engagement with similar content',
      'Filter bubbles may reduce exposure to unfamiliar ideas',
      'Counter-argument: discovery is higher than ever due to global access',
      'The distinction between curated serendipity and genuine surprise matters',
    ],
    retry_angle: 'Describe a time a truly random encounter changed something significant for you or someone else.',
    tags: ['technology', 'culture', 'algorithms'],
  },
  {
    topic: 'Post-Growth Economics',
    category: 'business',
    difficulty: 3,
    stance_type: 'argue',
    prompt_text: 'Is infinite economic growth possible or desirable on a finite planet?',
    context_bullets: [
      'Degrowth advocates argue welfare can rise while GDP falls in rich countries',
      'Orthodox economics argues growth can be decoupled from resource use via technology',
      'Current global poverty reduction has relied heavily on aggregate growth',
      'Measuring wellbeing by GDP has been widely criticised since the 1970s',
    ],
    retry_angle: 'What would need to be true for degrowth to work politically, not just economically?',
    tags: ['economics', 'environment', 'policy'],
  },
]

export const PROMPT_SEEDS_SQL = PROMPT_SEEDS.map((p, i) => {
  const bullets = JSON.stringify(p.context_bullets).replace(/'/g, "''")
  const tags = JSON.stringify(p.tags).replace(/'/g, "''")
  return `('${p.topic.replace(/'/g, "''")}', '${p.category}', ${p.difficulty}, '${p.stance_type}', '${p.prompt_text.replace(/'/g, "''")}', '${bullets}'::jsonb, '${p.retry_angle.replace(/'/g, "''")}', '${tags}'::jsonb, true)`
}).join(',\n')
